### ISSUE TITLE
Error at runtime

### ISSUE THREAD

**Issue by source83** [janusvr/janus-server#62]
username@jvr:~/janus-server# nodejs server.js 

/home/username/janus-server/server.js:153
            this._conn.query(sql, [thumbnail, roomUrl], (err, results) => {
                                                                        ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by bioid** [comment]
What version of node?
